### ISSUE TITLE
fetch_array issues

### ISSUE THREAD

**Issue by yrutschle** [cnangel/Conf-Libconfig#8]
Ok, I narrowed my problem with 1.0.2 down to two issues:

- fetch_array segfaults when fetching a name that is not present in the input file
- fetch_array returns an empty array when fetching a name that is present.

Attached two tiny scripts to exhibit the behaviours:
[test_cases.tar.gz](https://github.com/cnangel/Conf-Libconfig/files/12480084/test_cases.tar.gz)

Outputs on my system:
```
yves@hallertau:~/src/test_cases$ ./fetch_array 
$VAR1 = [];
yves@hallertau:~/src/test_cases$ ./segfault 
Segmentation fault
```

**Comment by cnangel** [comment]
* fetch_array segfaults when fetching a name that is not present in the input file: Fixed
 * fetch_array returns an empty array when fetching a name that is present:
```
conffile_option: ( "F", "conffile" );
```

Represents a list, not an array. If you want to get a list, use the value method instead of the fetch_array method. If you want to use the fetch_array method, the configuration needs to be written as:

```
conffile_option: [ "F", "conffile" ];
```

**Comment by yrutschle** [comment]
:+1: All good now. `fetch_array` used to work in that situation, I think, but `value` is more flexible, I think I'll move to using only that.
Thanks!
